language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
   secure: "uZcmpFN5fDeZ8mnJqYRx9luzaGw9qBAWuTyeDmpXA+p6tFjUbmYDrTW1pHeI+VUH/yxUHp7zqSTf/vt73rzNgD6ZGsbY2F/DwISA5W+r7oUoaiy6GPQsXLgeoschBNiPsgvmuAZKNAczzq7ufPeUYxjwX959z3t31psl11pG7cbnmhetIavHn3oMksiZNRGrpcAa1BHE4TDnYzsLxMfxkySaGMrhce3mmOAXfdP3ROXp1+peyfjouzh6hrse9WSP+tYS8oScd58H4biFpY3D8Wfw5XtxWCxq/aN9nUN14y+hU25yev+tJ6PD9bseFYx9wenVRvha67536IF6D6NrY5DPge7Li8nP42zXU6nBmt5qGJRM9SALq5SCxQ4n0bHeQ4mAFR/wGbmgpNAU8kgUKh2QELmwfl5QPYupudPkuqp79ZOGjzDK7u8CQOu0b9auBBHC7j2ZbuASNilXXQz4LJDWkr784IvQmD6lJ4y1gv+JGtCZrsHhJfJnd3m3aR06VkTCi2OQWbzW6Wq+qnnlZo7wz8dt/EPBcvMQVdvOVrL83eSHmceQTbJdtrZQB15dDaYQ5tTpeW5s+FRcnQDNSQ92DGRvn40J88RjB1N636u+o8QfCZi94vmor9yvfb/GSl/4M4syCB/ZMbA0m88WV7md602/0HBvbfpo94ZIN04="
  app: ksiazekm-jaa-eureka
  on:
    repo: ksiazekm/JAlgoArena-Eureka
